<h3 style="font-family: Times New Roman"><strong>PyTorch Tensor Objects Attributes and Methods</strong></h3>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    <br>
    This will cover the following operations of a tensor object:
    <ul style="font-family: Times New Roman; font-size:15px">
        <li>Converting NumPy arrays to PyTorch tensors</li>
        <li> Creating tensors from scratch</li>
        <li>Indexing and slicing</li>
        <li>Reshaping tensors (tensor views)</li>
        <li>Tensor arithmetic and basic operations</li>
        <li>Dot products</li>
        <li>Matrix multiplication</li>
        <li>Additional, more advanced operations</li>
    </ul>
</p>

<center><img src="figures/tensor.png" class="center" width="50%"></center>
<br>
<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters. Tensors are similar to NumPy’s ndarrays, <b>except that tensors can run on GPUs or other specialized hardware to accelerate computing</b>. 
</p>

<h4 style="font-family: Times New Roman"><strong>1. Converting NumPy arrays to PyTorch tensors</strong></h4>
<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type. Calculations between tensors can only happen if the tensors share the same dtype. In some cases tensors are used as a replacement for NumPy to use the power of GPUs (more on this later). Let's try to initialize a numpy array first!
</p>

In [1]:
import torch
import numpy as np
import sys

In [2]:
arr = np.array([1,2,3,4,5]).astype('float64')
print(arr)
print(arr.dtype)
print(type(arr))

[1. 2. 3. 4. 5.]
float64
<class 'numpy.ndarray'>


In [5]:
x = torch.from_numpy(arr)
# Equivalent to x = torch.as_tensor(arr)
print(x)

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)


In [6]:
# Print the datatype
print(x.dtype)

torch.float64


In [7]:
# Print the tensor object type
print(type(x))
print(x.type()) # this is more specific!

<class 'torch.Tensor'>
torch.DoubleTensor


In [8]:
arr2 = np.arange(0.,12.).reshape(4,3)
print(arr2)
print(type(arr2))

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
<class 'numpy.ndarray'>


In [9]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [10]:
rows, cols = 5, 5

# Create matrix using array comprehension
mat = np.matrix([[np.round(np.random.random(), 3) for _ in range(cols)] for _ in range(rows)])
print(mat)
print(type(mat))


xmat = torch.from_numpy(mat)
print(xmat)
print(type(xmat))

[[0.427 1.    0.431 0.295 0.619]
 [0.976 0.225 0.13  0.218 0.6  ]
 [0.685 0.746 0.834 0.9   0.941]
 [0.035 0.583 0.905 0.722 0.369]
 [0.769 0.707 0.499 0.89  0.208]]
<class 'numpy.matrix'>
tensor([[0.4270, 1.0000, 0.4310, 0.2950, 0.6190],
        [0.9760, 0.2250, 0.1300, 0.2180, 0.6000],
        [0.6850, 0.7460, 0.8340, 0.9000, 0.9410],
        [0.0350, 0.5830, 0.9050, 0.7220, 0.3690],
        [0.7690, 0.7070, 0.4990, 0.8900, 0.2080]], dtype=torch.float64)
<class 'torch.Tensor'>


In [11]:
# Check if an object is a tensor
torch.is_tensor(mat)

False

<table style="font-family: Times New Roman">
    <tr>
        <th colspan="4"><a href="https://pytorch.org/docs/stable/tensors.html"><h3>Tensor Datatypes</h3></a></th>
    </tr>
    <tr>
        <td><b>TYPE</b></td>
        <td><b>NAME</b></td>
        <td><b>EQUIVALENT</b></td>
        <td><b>TENSOR TYPE</b></td>
    </tr>
    <tr>
        <td>32-bit integer (signed)</td>
        <td>torch.int32</td>
        <td>torch.int</td>
        <td>IntTensor</td>
    </tr>
    <tr>
        <td>64-bit integer (signed)</td>
        <td>torch.int64</td>
        <td>torch.long</td>
        <td>LongTensor</td>
    </tr>
    <tr>
        <td>16-bit integer (signed)</td>
        <td>torch.int16</td>
        <td>torch.short</td>
        <td>ShortTensor</td>
    </tr>
    <tr>
        <td>32-bit floating point</td>
        <td>torch.float32</td>
        <td>torch.float</td>
        <td>FloatTensor</td>
    </tr>
    <tr>
        <td>64-bit floating point</td>
        <td>torch.float64</td>
        <td>torch.double</td>
        <td>DoubleTensor</td>
    </tr>
    <tr>
        <td>16-bit floating point</td>
        <td>torch.float16</td>
        <td>torch.half</td>
        <td>HalfTensor</td>
    </tr>
    <tr>
        <td>8-bit integer (signed)</td>
        <td>torch.int8</td>
        <td></td>
        <td>CharTensor</td>
    </tr>
    <tr>
        <td>8-bit integer (unsigned)</td>
        <td>torch.uint8</td>
        <td></td>
        <td>ByteTensor</td>
    </tr>
</table>


In [12]:
xmat.type()

'torch.DoubleTensor'

In [13]:
z = torch.from_numpy(np.array(np.random.random()).astype('int64'))
print(z)
z.type()

tensor(0)


'torch.LongTensor'

<a href='https://pytorch.org/docs/stable/torch.html#torch.from_numpy'><strong><tt>torch.from_numpy()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.as_tensor'><strong><tt>torch.as_tensor()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.tensor'><strong><tt>torch.tensor()</tt></strong></a><br>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
There are a number of different functions available for <a href='https://pytorch.org/docs/stable/torch.html#creation-ops'>creating tensors</a>. When using <a href='https://pytorch.org/docs/stable/torch.html#torch.from_numpy'><strong><tt>torch.from_numpy()</tt></strong></a> and <a href='https://pytorch.org/docs/stable/torch.html#torch.as_tensor'><strong><tt>torch.as_tensor()</tt></strong></a>, the PyTorch tensor and the source NumPy array share the same memory. This means that changes to one affect the other. However, the <a href='https://pytorch.org/docs/stable/torch.html#torch.tensor'><strong><tt>torch.tensor()</tt></strong></a> function always makes a copy.
</p>

In [14]:
# Using torch.from_numpy()
arr = np.arange(0,5)
t = torch.from_numpy(arr)
print(t)

tensor([0, 1, 2, 3, 4])


In [16]:
arr[2] = 77
print(t)

tensor([0, 1, 2, 3, 4])


In [15]:
# Using torch.tensor()
arr = np.arange(0,5)
t = torch.tensor(arr)
print(t)

tensor([0, 1, 2, 3, 4])


In [17]:
arr[2] = 77
print(t)

tensor([0, 1, 2, 3, 4])


<h4 style="font-family: Times New Roman"><strong>2. Creating tensors from scratch</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    <strong>Uninitialized tensors with</strong> <tt>.empty()</tt> <br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.empty'><strong><tt>torch.empty()</tt></strong></a> returns an <em>uninitialized</em> tensor. Essentially a block of memory is allocated according to the size of the tensor, and any values already sitting in the block are returned. This is similar to the behavior of <tt>numpy.empty()</tt>.
</p>

In [18]:
x = torch.empty(4, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


<h4 style="font-family: Times New Roman">Initialized tensors with <tt>.zeros()</tt> and <tt>.ones()</tt></h4>

<a href='https://pytorch.org/docs/stable/torch.html#torch.zeros'><strong><tt>torch.zeros(size)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.ones'><strong><tt>torch.ones(size)</tt></strong></a><br>
<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
It's a good idea to pass in the intended dtype.
</p>

In [19]:
x = torch.zeros(4, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [20]:
x = torch.ones(4, 4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


<h4 style="font-family: Times New Roman">Tensors from ranges</h4>

<a href='https://pytorch.org/docs/stable/torch.html#torch.arange'><strong><tt>torch.arange(start,end,step)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.linspace'><strong><tt>torch.linspace(start,end,steps)</tt></strong></a><br>
<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
Note that with <tt>.arange()</tt>, <tt>end</tt> is exclusive, while with <tt>linspace()</tt>, <tt>end</tt> is inclusive.
</p>

In [21]:
x = torch.arange(0,18,2).reshape(3,3)
print(x)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])


In [22]:
x = torch.linspace(0,18,12).reshape(3,4)
print(x)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])


<h4 style="font-family: Times New Roman">Tensors from data</h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<tt>torch.tensor()</tt> will choose the dtype based on incoming data:
</p>

In [23]:
x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.dtype)
print(x.type())
#changing datatypes
x.type(torch.int32)

tensor([1, 2, 3, 4])
torch.int64
torch.LongTensor


tensor([1, 2, 3, 4], dtype=torch.int32)

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
You can also pass the dtype in as an argument. For a list of dtypes visit <a href="https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype">https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype</a>
</p>

In [24]:
x = torch.tensor([8,9,-3], dtype=torch.int)
print(x)
print(x.dtype)
print(x.type())

tensor([ 8,  9, -3], dtype=torch.int32)
torch.int32
torch.IntTensor


<h4 style="font-family: Times New Roman">Changing the dtype of existing tensors</h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
Don't be tempted to use <tt>x = torch.tensor(x, dtype=torch.type)</tt> as it will raise an error about improper use of tensor cloning.<br>
Instead, use the tensor <tt>.type()</tt> method.
</p>

In [25]:
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


<h4 style="font-family: Times New Roman">Random number tensor</h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand'><strong><tt>torch.rand(size)</tt></strong></a> returns random samples from a uniform distribution over [0, 1)<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn'><strong><tt>torch.randn(size)</tt></strong></a> returns samples from the "standard normal" distribution [σ = 1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;Unlike <tt>rand</tt> which is uniform, values closer to zero are more likely to appear.<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint'><strong><tt>torch.randint(low,high,size)</tt></strong></a> returns random integers from low (inclusive) to high (exclusive)
</p>

In [26]:
x = torch.rand(4, 3)
print(x)

tensor([[0.5815, 0.1410, 0.1781],
        [0.1308, 0.5832, 0.5384],
        [0.2829, 0.2353, 0.2147],
        [0.4034, 0.4756, 0.7759]])


In [27]:
x = torch.randn(4, 3)
print(x)

tensor([[ 0.6299, -0.5655,  0.8935],
        [-0.4786, -0.1238,  2.1943],
        [-0.4932, -0.4761,  1.1442],
        [ 0.4363,  0.4554,  1.5660]])


In [ ]:
x = torch.randint(0, 5, (4, 3))
print(x)

<h4 style="font-family: Times New Roman">Random number tensors that follow the input size</h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand_like'><strong><tt>torch.rand_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn_like'><strong><tt>torch.randn_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint_like'><strong><tt>torch.randint_like(input,low,high)</tt></strong></a><br> these return random number tensors with the same size as <tt>input</tt>
</p>

In [28]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [29]:
x2 = torch.randn_like(x)
print(x2)

tensor([[-0.4435, -0.6278, -1.3252, -2.1763,  0.8072],
        [-2.0179, -0.6558,  1.3250, -0.6013,  1.7245]])


<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
The same syntax can be used with<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.zeros_like'><strong><tt>torch.zeros_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.ones_like'><strong><tt>torch.ones_like(input)</tt></strong></a>
</p>

In [30]:
x3 = torch.ones_like(x2)
print(x3)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [31]:
x4 = torch.zeros_like(x3)
print(x4)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


<h4 style="font-family: Times New Roman">Setting the random seed</h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<a href='https://pytorch.org/docs/stable/torch.html#torch.manual_seed'><strong><tt>torch.manual_seed(int)</tt></strong></a> is used to obtain reproducible results
</p>

In [32]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [36]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


<h4 style="font-family: Times New Roman">Tensor attributes</h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    Besides <tt>dtype</tt>, we can look at other <a href='https://pytorch.org/docs/stable/tensor_attributes.html'>tensor attributes</a> like <tt>shape</tt>, <tt>device</tt> and <tt>layout</tt>.
</p>

In [49]:
x.shape

torch.Size([2, 3])

In [50]:
x.size()  # equivalent to x.shape

torch.Size([2, 3])

In [53]:
x.to('cuda')

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]], device='cuda:0')

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    PyTorch supports use of multiple <a href='https://pytorch.org/docs/stable/tensor_attributes.html#torch-device'>devices</a>, harnessing the power of one or more GPUs in addition to the CPU. We won't explore that here, but you should know that operations between tensors can only happen for tensors installed on the same device.
</p>

In [54]:
x.layout

torch.strided

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">PyTorch has a class to hold the <a href='https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.layout'>memory layout</a> option. The default setting of <a href='https://en.wikipedia.org/wiki/Stride_of_an_array'>strided</a> will suit our purposes throughout the course.
</p>

<h4 style="font-family: Times New Roman"><strong>3. Indexing and Slicing</strong></h4>
<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
Extracting specific values from a tensor works just the same as with NumPy arrays.
</p>

In [55]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [56]:
# Grabbing the right hand column values
x[:,1]

tensor([1, 3, 5])

In [57]:
# Grabbing the right hand column as a (3,1) slice
x[:,1:]

tensor([[1],
        [3],
        [5]])

<h4 style="font-family: Times New Roman"><strong>4. Reshape tensors with <tt>.view()</tt></strong></h4>
<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<a href='https://pytorch.org/docs/master/tensors.html#torch.Tensor.view'><strong><tt>view()</tt></strong></a> and <a href='https://pytorch.org/docs/master/torch.html#torch.reshape'><strong><tt>reshape()</tt></strong></a> do essentially the same thing by returning a reshaped tensor without changing the original tensor in place.<br>
There's a good discussion of the differences <a href='https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch'>here</a>.</p>

In [58]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [59]:
y = x.view(2,5)
y[0, 0] = 5
y

tensor([[5, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [60]:
# x is changed by changing y, which shares the data...
x

tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a = x.reshape(5,2)
a[0, 0] = 99

In [62]:
x

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

<h4 style="font-family: Times New Roman">Adopt another tensor's shape with <tt>.view_as()</h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    <a href='https://pytorch.org/docs/master/tensors.html#torch.Tensor.view_as'><strong><tt>view_as(input)</tt></strong></a> only works with tensors that have the same number of elements.
</p>

In [63]:
z = torch.ones((5, 2))
x.view_as(z)

tensor([[99,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]])

In [64]:
z

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

<h4 style="font-family: Times New Roman"><strong>5. Tensor Arithmetic</strong></h4>
<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
Adding tensors can be performed a few different ways depending on the desired result.<br>
As a simple expression:</p>

In [65]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([5., 7., 9.])


<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    As arguments passed into a torch operation:
</p>

In [66]:
print(torch.add(a, b))

tensor([5., 7., 9.])


<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    With an output tensor passed in as an argument:
</p>

In [67]:
result = torch.empty(3)
torch.add(a, b, out=result)  # equivalent to result=torch.add(a,b)
print(result)

tensor([5., 7., 9.])


In [68]:
a.add_(b)  # equivalent to a=torch.add(a,b)
print(a)

tensor([5., 7., 9.])


<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<strong>NOTE:</strong> Any operation that changes a tensor in-place is post-fixed with an underscore _.
    <br>In the above example: <tt>a.add_(b)</tt> changed <tt>a</tt>.
</p>

<h4 style="font-family: Times New Roman"><strong>Basic Tensor Operations</strong></h4>
<center>
<table style="display: inline-block; font-family: Times New Roman">
    <caption style="text-align: center"><strong>ARITHMETIC</strong></caption>
    <tr>
        <td><b>Operation</b></td>
        <td><b>Function</b></td>
        <td><b>Description</b></td>
    </tr>
    <tr>
        <td>a + b</td>
        <td>a.add(b)</td>
        <td>element wise addition</td>
    </tr>
    <tr>
        <td>a - b</td>
        <td>a.sub(b)</td>
        <td>subtraction</td>
    </tr>
    <tr>
        <td>a * b</td>
        <td>a.mul(b)</td>
        <td>multiplication</td>
    </tr>
    <tr>
        <td>a / b</td>
        <td>a.div(b)</td>
        <td>division</td>
    </tr>
    <tr>
        <td>a % b</td>
        <td>a.fmod(b)</td>
        <td>modulo (remainder after division)</td>
    </tr>
    <tr>
        <td>a<sup>b</sup></td>
        <td>a.pow(b)</td>
        <td>power</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td></td>
        <td></td>
    </tr>
</table>
</center>

<center>
<table style="display: inline-block; font-family: Times New Roman">
<caption style="text-align: center"><strong>MONOMIAL OPERATIONS</strong></caption>
<tr><th>Operation</th><th>Function</th><th>Description</th></tr>
<tr><td>|a|</td><td>torch.abs(a)</td><td>absolute value</td></tr>
<tr><td>1/a</td><td>torch.reciprocal(a)</td><td>reciprocal</td></tr>
<tr><td>$\sqrt{a}$</td><td>torch.sqrt(a)</td><td>square root</td></tr>
<tr><td>log(a)</td><td>torch.log(a)</td><td>natural log</td></tr>
<tr><td>e<sup>a</sup></td><td>torch.exp(a)</td><td>exponential</td></tr>
<tr><td>12.34  ==>  12.</td><td>torch.trunc(a)</td><td>truncated integer</td></tr>
<tr><td>12.34  ==>  0.34</td><td>torch.frac(a)</td><td>fractional component</td></tr>
</table>
</center>

<center>
<table style="display: inline-block; font-family: Times New Roman">
<caption style="text-align: center"><strong>SUMMARY STATISTICS</strong></caption>
<tr><th>Operation</th><th>Function</th><th>Description</th></tr>
<tr><td>$\sum a$</td><td>torch.sum(a)</td><td>sum</td></tr>
<tr><td>$\bar a$</td><td>torch.mean(a)</td><td>mean</td></tr>
<tr><td>a<sub>max</sub></td><td>torch.max(a)</td><td>maximum</td></tr>
<tr><td>a<sub>min</sub></td><td>torch.min(a)</td><td>minimum</td></tr>
<tr><td colspan="3">torch.max(a,b) returns a tensor of size a<br>containing the element wise max between a and b</td></tr>
</table>
</center>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<strong>NOTE:</strong>  Most arithmetic operations require float values. Those that do work with integers return integer tensors.<br>
For example, <tt>torch.div(a,b)</tt> performs floor division (truncates the decimal) for integer types, and classic division for floats.</p>

<h4 style="font-family: Times New Roman"><strong>6. Dot Products</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
A <a href='https://en.wikipedia.org/wiki/Dot_product'>dot product</a> is the sum of the products of the corresponding entries of two 1D tensors. If the tensors are both vectors, the dot product is given as:<br>
<br>
$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d & e & f \end{bmatrix} = ad + be + cf$
<br>
If the tensors include a column vector, then the dot product is the sum of the result of the multiplied matrices. For example:<br>
$\begin{bmatrix} a & b & c \end{bmatrix} \;\cdot\; \begin{bmatrix} d \\ e \\ f \end{bmatrix} = ad + be + cf$<br><br>
Dot products can be expressed as <a href='https://pytorch.org/docs/stable/torch.html#torch.dot'><strong><tt>torch.dot(a,b)</tt></strong></a> or <tt>a.dot(b)</tt> or <tt>b.dot(a)</tt>
</p>

In [69]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a.dot(b))

tensor(32.)


<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<strong>NOTE:</strong>  There's a slight difference between <tt>torch.dot()</tt> and <tt>numpy.dot()</tt>. While <tt>torch.dot()</tt> only accepts 1D arguments and returns a dot product, <tt>numpy.dot()</tt> also accepts 2D arguments and performs matrix multiplication. We show matrix multiplication below.</p>

<h4 style="font-family: Times New Roman"><strong>7. Matrix Multiplication</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
2D <a href='https://en.wikipedia.org/wiki/Matrix_multiplication'>Matrix multiplication</a> is possible when the number of columns in tensor <strong><tt>A</tt></strong> matches the number of rows in tensor <strong><tt>B</tt></strong>. In this case, the product of tensor <strong><tt>A</tt></strong> with size $(x,y)$ and tensor <strong><tt>B</tt></strong> with size $(y,z)$ results in a tensor of size $(x,z)$
<br>
$\begin{bmatrix} a & b & c \\
d & e & f \end{bmatrix} \;\times\; \begin{bmatrix} m & n \\ p & q \\ r & s \end{bmatrix} = \begin{bmatrix} (am+bp+cr) & (an+bq+cs) \\
(dm+ep+fr) & (dn+eq+fs) \end{bmatrix}$</div></div>
<br>
Matrix multiplication can be computed using <a href='https://pytorch.org/docs/stable/torch.html#torch.mm'><strong><tt>torch.mm(a,b)</tt></strong></a> or <tt>a.mm(b)</tt> or <tt>a @ b</tt>
</p>

In [70]:
a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)

print('a: ',a.size())
print('b: ',b.size())
print('a x b: ',torch.mm(a,b).size())

a:  torch.Size([2, 3])
b:  torch.Size([3, 2])
a x b:  torch.Size([2, 2])


In [71]:
print(torch.mm(a,b))

tensor([[56., 62.],
        [80., 89.]])


In [72]:
print(a.mm(b))

tensor([[56., 62.],
        [80., 89.]])


In [73]:
print(a @ b)

tensor([[56., 62.],
        [80., 89.]])


<h4 style="font-family: Times New Roman">Matrix multiplication with broadcasting</h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
    Matrix multiplication that involves <a href='https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics'>broadcasting</a> can be computed using <a href='https://pytorch.org/docs/stable/torch.html#torch.matmul'><strong><tt>torch.matmul(a,b)</tt></strong></a> or `a.matmul(b)` or `a @ b`
</p>

In [74]:
t1 = torch.randn(2, 3, 4)
t2 = torch.randn(4, 5)

print(torch.matmul(t1, t2).size())

torch.Size([2, 3, 5])


<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
However, the same operation raises a <tt><strong>RuntimeError</strong></tt> with <tt>torch.mm()</tt>:
</p>

In [75]:
# print(torch.mm(t1, t2).size())
t1 = torch.randn(2, 3)
t1

tensor([[-0.7409,  0.3618,  1.9199],
        [-0.2254, -0.3417,  0.3040]])

In [76]:
t2 = torch.randn(3).reshape(3,1)
t2

tensor([[-0.6890],
        [-1.1267],
        [-0.2858]])

In [77]:
print(torch.mm(t1, t2))

tensor([[-0.4458],
        [ 0.4534]])


<h4 style="font-family: Times New Roman"><strong>8. Additional Operations</strong></h4>
<h4 style="font-family: Times New Roman"><strong>&emsp;&emsp;L2 or Euclidean Norm</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
&emsp;&emsp;See <a href='https://pytorch.org/docs/stable/torch.html#torch.norm'><strong><tt>torch.norm()</tt></strong></a>
<br>
&emsp;&emsp;The <a href='https://en.wikipedia.org/wiki/Norm_(mathematics)#Euclidean_norm'>Euclidian Norm</a> gives the vector norm of $x$ where $x=(x_1,x_2,...,x_n)$.<br>
&emsp;&emsp;It is calculated as
<br>
<br>
&emsp;&emsp;${\displaystyle \left\|{\boldsymbol {x}}\right\|_{2}:={\sqrt {x_{1}^{2}+\cdots +x_{n}^{2}}}}$
<br>
<br>
&emsp;&emsp;When applied to a matrix, <tt>torch.norm()</tt> returns the <a href='https://en.wikipedia.org/wiki/Matrix_norm#Frobenius_norm'>Frobenius norm</a> by default.
</p>

In [78]:
x = torch.tensor([2.,5.,8.,14.])
x.norm()

tensor(17.)

<h4 style="font-family: Times New Roman"><strong>&emsp;&emsp;Number of Elements</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
&emsp;&emsp;See <a href='https://pytorch.org/docs/stable/torch.html#torch.numel'><strong><tt>torch.numel()</tt></strong></a>
<br>
&emsp;&emsp;Returns the number of elements in a tensor.
</p>

In [79]:
x = torch.ones(3,7)
x.numel()

21

<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 5</strong></h4>

**1. Perform Standard Imports**

<br>

**2. Create a function called `set_seed()` that accepts `seed: int` as a parameter, this function must return nothing but just set the seed to a certain value.**

<br>

**3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the `set_seed()` function and use `42` as the seed parameter.**

<br>

**4. Create a tensor "x" from the array above**

<br>

**5. Change the dtype of x from `int32` to `int64`**

<br>

**6. Reshape `x` into a 3x2 tensor** <br> There are several ways to do this.

<br>

**7. Return the right-hand column of tensor `x`**

<br>

**8. Without changing x, return a tensor of square values of `x`** <br> There are several ways to do this.

<br>

**9. Create a tensor `y` with the same number of elements as `x`, that can be matrix-multiplied with `x`** <br> Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed. <br> Think about what shape it should have to permit matrix multiplication.

<br>

**10. Find the matrix product of `x` and `y`.**

</div>